BEGIN;

INSERT INTO Person(person_name) VALUES ('Person 1');
INSERT INTO Person(person_name) VALUES ('Person 2');
INSERT INTO Person(person_name) VALUES ('Person 3');
INSERT INTO Person(person_name) VALUES ('Person 4');
INSERT INTO Person(person_name) VALUES ('Person 5');
INSERT INTO Person(person_name) VALUES ('Person 6');

INSERT INTO Team(team_name, active) VALUES ('Team 1', true);
INSERT INTO Team(team_name, active) VALUES ('Team 2', true);

INSERT INTO Employee(person_id, position, team_id) VALUES (1, 'employed', 1);
INSERT INTO Employee(person_id, position, team_id) VALUES (2, 'employed', 1);
INSERT INTO Employee(person_id, position, team_id) VALUES (3, 'employed', 2);
INSERT INTO Employee(person_id, position, team_id) VALUES (4, 'employed', 2);

INSERT INTO Company(company_name) VALUES ('Nintendo');

INSERT INTO Partner(person_id, company_id, position) VALUES (5, 1, 'unemployed');
INSERT INTO Partner(person_id, company_id, position) VALUES (6, 1, 'unemployed');

INSERT INTO Room(name, cost_per_hour) VALUES ('Room 1', 100);
INSERT INTO Room(name, cost_per_hour) VALUES ('Room 2', 200);
INSERT INTO Room(name, cost_per_hour) VALUES ('Room 3', 1000);
INSERT INTO Room(name, cost_per_hour) VALUES ('Room 4', 30);
INSERT INTO Room(name, cost_per_hour) VALUES ('Room 5', 0);

INSERT INTO Facility(room_id, name) VALUES (1, 'Projector');
INSERT INTO Facility(room_id, name) VALUES (2, 'Whiteboard');
INSERT INTO Facility(room_id, name) VALUES (3, 'Blackboard');
INSERT INTO Facility(room_id, name) VALUES (3, 'Table');
INSERT INTO Facility(room_id, name) VALUES (4, 'CRT TV');
INSERT INTO Facility(room_id, name) VALUES (5, 'Table');

INSERT INTO Booking(room_id, person_id, team_id, start, finish, total_cost)
VALUES (1, 3, 2, ts'2018-02-16 12:00:00', ts'2018-02-16 14:00:00', 200);
INSERT INTO Booking(room_id, person_id, team_id, start, finish, total_cost)
VALUES (1, 2, 1, ts'2018-02-16 14:00:00', ts'2018-02-16 15:00:00', 100);
INSERT INTO Booking(room_id, person_id, team_id, start, finish, total_cost)
VALUES (3, 1, 1, ts'2018-02-16 13:00:00', ts'2018-02-16 14:00:00', 1000);

INSERT INTO Participant(person_id, booking_id) VALUES (3, 1);
INSERT INTO Participant(person_id, booking_id) VALUES (2, 1);
INSERT INTO Participant(person_id, booking_id) VALUES (1, 2);
INSERT INTO Participant(person_id, booking_id) VALUES (4, 2);
INSERT INTO Participant(person_id, booking_id) VALUES (5, 2);

COMMIT;
